server:
  port : 8084
  error:
    include-message: always
    include-stacktrace: never
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: '${EUREKA_CONNECTION_URL:http://localhost:8761}/eureka'
    fetch-registry: true
    register-with-eureka: true
spring:
  application:
    name: fatura
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: '${DATABASE_CONNECTION_URL:jdbc:mysql://localhost:3303/faturadb}'
    username: mysql
    password: mysql
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql

management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics, prometheus

clients:
  contacorrente: '${CONTA_CORRENTE_URL:http://localhost:8083/conta-corrente}'
  debito: '${DEBITO_URL:http://localhost:8082/debito}'